global:
  scrape_interval:     5s # Set the scrape interval to every 5 seconds.
  evaluation_interval: 5s # Evaluate rules every 5 seconds.
scrape_configs:
  - job_name: 'msref-accountsms'
    metrics_path: '/actuator/prometheus'
    static_configs:
    - targets: ['msref-accountsms:8081']
  - job_name: 'msref-loans'
    metrics_path: '/actuator/prometheus'
    static_configs:
    - targets: ['msref-loans:8090']
  - job_name: 'msref-cards'
    metrics_path: '/actuator/prometheus'
    static_configs:
    - targets: ['msref-cards:9000']