services:

  msref-zipkin:
    image: openzipkin/zipkin
    mem_limit: 700m
    ports:
      - "9411:9411"
    networks:
     - schlimmbank

  msref-config:
    image: nschlimm/msref-config:latest
    mem_limit: 700m
    depends_on:
      - msref-zipkin
    ports:
      - "8071:8071"
    networks:
     - schlimmbank
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_ZIPKIN_BASEURL: http://msref-zipkin:9411/
      
  msref-discovery:
    image: nschlimm/msref-discovery:latest
    mem_limit: 700m
    ports:
      - "8070:8070"
    networks:
      - schlimmbank
    depends_on:
      - msref-config
    deploy:
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://msref-config:8071/
      SPRING_ZIPKIN_BASEURL: http://msref-zipkin:9411/
  
  msref-accountsms:
    image: nschlimm/msref-accountsms:latest
    mem_limit: 700m
    ports:
      - "8081:8081"
    networks:
      - schlimmbank
    depends_on:
      - msref-config
      - msref-discovery
    deploy:
      restart_policy:
        condition: on-failure
        delay: 20s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://msref-config:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://msref-discovery:8070/eureka/
      SPRING_ZIPKIN_BASEURL: http://msref-zipkin:9411/
  
  msref-accountsms1:
    image: nschlimm/msref-accountsms:latest
    mem_limit: 700m
    ports:
      - "8080:8081"
    networks:
      - schlimmbank
    depends_on:
      - msref-config
      - msref-discovery
    deploy:
      restart_policy:
        condition: on-failure
        delay: 20s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://msref-config:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://msref-discovery:8070/eureka/
      SPRING_ZIPKIN_BASEURL: http://msref-zipkin:9411/
  
  msref-loans:
    image: nschlimm/msref-loans:latest
    mem_limit: 700m
    ports:
      - "8090:8090"
    networks:
      - schlimmbank
    depends_on:
      - msref-config
      - msref-discovery
    deploy:
      restart_policy:
        condition: on-failure
        delay: 20s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://msref-config:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://msref-discovery:8070/eureka/
      SPRING_ZIPKIN_BASEURL: http://msref-zipkin:9411/
    
  msref-cards:
    image: nschlimm/msref-cards:latest
    mem_limit: 700m
    ports:
      - "9000:9000"
    networks:
      - schlimmbank
    depends_on:
      - msref-config
      - msref-discovery
    deploy:
      restart_policy:
        condition: on-failure
        delay: 20s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://msref-config:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://msref-discovery:8070/eureka/
      SPRING_ZIPKIN_BASEURL: http://msref-zipkin:9411/
      
  msref-gateway:
    image: nschlimm/msref-gateway:latest
    mem_limit: 700m
    ports:
      - "8072:8072"
    networks:
      - schlimmbank
    depends_on:
      - msref-config
      - msref-discovery
      - msref-cards
      - msref-loans
      - msref-accountsms
    deploy:
      restart_policy:
        condition: on-failure
        delay: 45s
        max_attempts: 3
        window: 180s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://msref-config:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://msref-discovery:8070/eureka/
      SPRING_ZIPKIN_BASEURL: http://msref-zipkin:9411/
  
networks:
  schlimmbank: {}
  