apiVersion: apps/v1
kind: Deployment
metadata:
  name: msref-cards-deployment
  labels:
    app: msref-cards
spec:
  replicas: 1
  selector:
    matchLabels:
      app: msref-cards
  template:
    metadata:
      labels:
        app: msref-cards
    spec:
      containers:
      - name: msref-cards
        image: nschlimm/msref-cards:latest
        ports:
        - containerPort: 9000
        env:
        - name: SPRING_PROFILES_ACTIVE
          valueFrom: 
            configMapKeyRef:
              name: nschlimm-configmap
              key: SPRING_PROFILES_ACTIVE
        - name: SPRING_ZIPKIN_BASEURL
          valueFrom: 
            configMapKeyRef:
              name: nschlimm-configmap
              key: SPRING_ZIPKIN_BASEURL
        - name: SPRING_CONFIG_IMPORT
          valueFrom: 
            configMapKeyRef:
              name: nschlimm-configmap
              key: SPRING_CONFIG_IMPORT
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          valueFrom: 
            configMapKeyRef:
              name: nschlimm-configmap
              key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
---
apiVersion: v1
kind: Service
metadata:
  name: msref-cards-service
spec:
  selector:
    app: msref-cards
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
